# Site settings
title: Sri Lanka Demands
tag_text: Sri Lanka Demands
description: A markup site to track the progress of the protests on LK Economic Crisis 

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
