# Site settings
title: Sri Lanka Demands
tag_text: Sri Lanka Demands
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
